language: swift
osx_image: xcode11
xcode_project: FaceDetection.xcodeproj
xcode_scheme: FaceDetection
script:
    - xcodebuild clean build -sdk iphonesimulator -project FaceDetection.xcodeproj -scheme FaceDetection CODE_SIGNING_REQUIRED=NO
